package br.com.kascosys.vulkanconnectv317.constants

const val CONNECTED_TO_WRONG_AP_FILTER = "CONNECTED_TO_WRONG_AP_FILTER"

const val CONNECTION_LOST_FILTER = "CONNECTION_LOST_FILTER"

const val CONNECTION_UNAVAILABLE_FILTER = "CONNECTION_UNAVAILABLE_FILTER"

const val CONNECTION_SUCCESS_FILTER = "CONNECTION_SUCCESS_FILTER"

const val CONNECTION_TIMEOUT_FILTER = "CONNECTION_TIMEOUT_FILTER"